name: My Workflow

on:
  push:
    branches:
      - main
env:
  API_KEY: ${{ secrets.API_KEY }}
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
        pip install openai==0.28
        pip install pandas
        pip install matplotlib
        pip install yfinance
        pip install numpy
        pip install streamlit
            
      
    - name: Run script
      run: python main.py

    
  
  
