name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
        pip install openai==0.28
        pip install pandas
            
      
    - name: Run script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python main.py

    
  
  
