name: Run Tests
on: workflow_dispatch

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: testing sec
        run: echo "$API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
        
    
  
  
